# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Food Friends' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Food Friends

pod 'Firebase/Auth'
pod 'pop', '~> 1.0'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod "ESTabBarController-swift"


end
