# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Food Friends' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Food Friends
pod "Macaw", "0.9.1"
pod 'ReadMoreTextView'

end
